### ISSUE TITLE
Investigate /gpWebcam endpoint

### ISSUE THREAD

**Issue by gordonel** [KonradIT/goprowifihack#206]
Not really a problem, but a suggestion.

GoPro released GoPro Webcam software for HERO8/9 and added an endpoint at `/gp/gpWebcam`. I figured out `/gp/gpWebcam/START` and `/gp/gpWebcam/STOP` commands. `gp/gpWebcam/status` returns an empty array.

Also, it completely ignores any settings set via `gpControl`. I have a HERO9 and can collaborate on this if you'd like

**Comment by KonradIT** [comment]
Hi, I have a HERO9 as well, I am preparing a full documentation of gpWebcam and all of the Hero9 commands via BT-LE and WiFi (some WiFi commands have been deprecated).

**Comment by gordonel** [comment]
Good to know. Found something in https://github.com/gurgelx/GoProBetaHelper/blob/master/GoProConnector/GoProClient.cs

**Comment by KonradIT** [comment]
Working on it... https://twitter.com/konrad_it/status/1309072047272873985

**Comment by rmoriz** [comment]
curl http://172.28.128.51/gp/gpWebcam/STOP

curl http://172.28.128.51/gp/gpControl/setting/43/0
curl http://172.28.128.51/gp/gpControl/setting/43/4
curl http://172.28.128.51/gp/gpControl/setting/43/6

curl http://172.28.128.51/gp/gpWebcam/STARTLTP?res=12

**Comment by gordonel** [comment]
> curl http://172.28.128.51/gp/gpWebcam/STARTLTP?res=12

This is something new

**Comment by KonradIT** [comment]
Don't use LTP, that's for low resolution preview.

**Comment by KonradIT** [comment]
Also, I have a PR open in gopro-py-api: https://github.com/KonradIT/gopro-py-api/pull/148

Feel free to fork the project and add your webcam examples there.

So far, my planned usage of gpWebcam is:

- Use FFmpeg and v4l2loopback to create a native /dev/videoX driver, and use NetworkManager dispatch script to do Webcam START when the camera is plugged into my PC, then have an applet to start/stop the FFmpeg thread and turn on/off camera, change resolution, FOV...
- Use FFmpeg to record 30 second video off the GoPro or take a screencap all via USB and upload to my NAS, this will be running on a raspberry pi because I need to monitor my crops

**Comment by KonradIT** [comment]
Wow, gpWebcam is truly the gift that keeps on giving. Just made a flask app that displays my media nicely in a web browser and can play back/delete/download. http://github.com/konradit/goprodashboard

This is miles ahead of MTP connection.

**Comment by KonradIT** [comment]
Closing this as the information has been added: https://github.com/KonradIT/goprowifihack/commit/4dcd1fb32905d88c8725b380874afe11d822a23a

**Comment by gordonel** [comment]
Thanks @KonradIT. Do you know if FOV and resolution are the only settings you can change for gpWebcam or is there a way to use manual exposure and, say, flat colour?

**Comment by KonradIT** [comment]
Cannot seem to change any setting over Webcam mode when the webcam is active, which is a huge bummer. This is what I get:

````
{
"version": "6.00",
"path_info": "setting/102/6",
"query_string": "",
"error_code":-1,
"error_msg": "500 Internal Server Error
",
"function": "gpcontrol_cgi_handler",
"line": 190
}
````

Perhaps GoPro can add custom ProTune controls to Webcam because I want to lower the max/min ISO to 100-400 like I always have on video mode, have a warmer white balance and use flat color.

**Comment by gordonel** [comment]
it seems to be the same on the latest firmware. Can you verify?
