### ISSUE TITLE
GOPRO OMNI firmware?

### ISSUE THREAD

**Issue by roysbike** [KonradIT/goprowifihack#58]
####Problem:
I need firmware OMNI  for gopro4 
####Details:

* GoPro Camera(s):
* Firmware Version:
* Steps to reproduce:
* Happens every time? [Y/N]:

**Comment by KonradIT** [comment]
Hi,

This repo is dedicated to documenting and reverse engineering the **wireless** protocol that GoPro HERO cameras use to communicate with the handheld Capture app. OMNI VR rig is out of the scope.

With firmware, do you mean the firmware on the camera, because the HERO4 updated to the latest firmware supports OMNI's HEROBUS protocol AFAIK, if you mean the firmware that is on the connector bus or other electrical component then I don't know since I don't have or have access to an OMNI VR Rig.

**Comment by roysbike** [comment]
I access omni firmware OmniSecondaryCamera https://yadi.sk/d/1Pxc2xy533Xpr9
And OmniPrimaryCameraFirmware https://yadi.sk/d/Pn5SDSpx33XwEg. You may need to.

**Comment by roysbike** [comment]
I want make analog omni rig. But 6 cameras are collected in an array. Synchronisation is via the bus gopro. But switching circuit I do not have. How do you think it is possible to know the connection type of connector? If there is a firmware omni?

**Comment by KonradIT** [comment]
You should ask GoPro Support center, I don't have this kind of information.
